spring:
  application:
    name: load-generator

server:
  port: 8081

load:
  target:
    url: ${TARGET_URL:http://localhost:8080}
  duration:
    minutes: ${LOAD_DURATION_MINUTES:15}

logging:
  level:
    ru.sfedu.sharding.load: INFO
